# Generated by Django 2.2 on 2019-10-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20190828_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_appendix',
            fields=[
                ('detail', models.TextField(default='[]', verbose_name='私人附件详情')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '私人附件',
                'verbose_name_plural': '私人附件',
                'permissions': {('upload_personal_appendix', '下载私人附件'), ('edit_personal_appendix', '编辑私人附件'), ('download_personal_appendix', '下载私人附件')},
            },
        ),
    ]
